// Machine-generated by `npm run pipeline:signals`. Do not edit.
import type { Signal } from "@/lib/domain";

export const GENERATED_SIGNALS: readonly Signal[] = [
  {
    "identity": {
      "id": "agentic-ai",
      "slug": "agentic-ai",
      "title": "Agentic AI",
      "headline": "Software is becoming autonomous.",
      "summary": "Teams shipping agent workflows move faster. Those waiting risk falling behind within two quarters."
    },
    "classification": {
      "domain": "Artificial Intelligence",
      "tags": [],
      "interest": "artificial-intelligence"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 1248,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-9%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 50,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Over the next year, agent frameworks will become default infrastructure for software teams. Late adopters will compete on integration speed, not model access alone.",
      "forecastConfidence": "high"
    },
    "relationships": {
      "relatedSignals": [
        "cuda",
        "cloud-infrastructure",
        "cybersecurity",
        "autonomous-systems"
      ],
      "relatedCompanies": [
        "OpenAI",
        "Microsoft",
        "Google",
        "Anthropic"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "entrepreneur",
        "investor",
        "student"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "artificial-intelligence"
      ]
    },
    "presentation": {
      "featured": true,
      "narrative": "Rapid Adoption",
      "sparkline": [
        42,
        48,
        45,
        55,
        58,
        62,
        68,
        74,
        82,
        91,
        97
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Agentic systems are moving from demos to production workflows faster than most organizations can retool. The window to build internal capability is narrowing as incumbents embed autonomy into core products."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "cuda",
      "slug": "cuda",
      "title": "CUDA",
      "headline": "AI compute demand is accelerating.",
      "summary": "Every frontier model depends on GPU scale. Capacity now decides who ships first."
    },
    "classification": {
      "domain": "Cloud & Compute",
      "tags": [],
      "interest": "cloud-computing"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 982,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "-45%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "+12%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 45,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Inference demand will outpace training within eighteen months. Firms that secure long-term compute contracts now will ship features others cannot.",
      "forecastConfidence": "high"
    },
    "relationships": {
      "relatedSignals": [
        "agentic-ai",
        "semiconductor-supply-chain",
        "cloud-infrastructure"
      ],
      "relatedCompanies": [
        "NVIDIA",
        "Microsoft",
        "Google",
        "Amazon"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "entrepreneur",
        "investor"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "cloud-computing"
      ]
    },
    "presentation": {
      "featured": true,
      "narrative": "Infrastructure Expansion",
      "sparkline": [
        58,
        62,
        60,
        68,
        72,
        75,
        80,
        84,
        88,
        92,
        95
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "GPU compute is the binding constraint on AI progress. Every major model release intensifies competition for CUDA-class capacity and the talent to operate it."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "semiconductor-supply-chain",
      "slug": "semiconductor-supply-chain",
      "title": "Semiconductor Supply Chain",
      "headline": "Chip supply is now strategic power.",
      "summary": "Nations and firms race to secure advanced packaging before the next capacity crunch."
    },
    "classification": {
      "domain": "Supply Chain",
      "tags": [],
      "interest": "supply-chain"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 715,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "-50%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-5%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 42,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Regional diversification will accelerate through 2027. Companies without dual-source strategies face multi-quarter delays on every hardware roadmap.",
      "forecastConfidence": "high"
    },
    "relationships": {
      "relatedSignals": [
        "cuda",
        "quantum-computing",
        "robotics"
      ],
      "relatedCompanies": [
        "TSMC",
        "NVIDIA",
        "Intel",
        "Samsung"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "entrepreneur",
        "investor"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "supply-chain"
      ]
    },
    "presentation": {
      "featured": true,
      "narrative": "Infrastructure Expansion",
      "sparkline": [
        52,
        55,
        58,
        62,
        65,
        70,
        74,
        78,
        82,
        85,
        88
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Advanced packaging and geopolitical alignment now determine who can build AI at scale. Supply security has become a board-level risk, not a procurement detail."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "humanoid-robotics",
      "slug": "humanoid-robotics",
      "title": "Humanoid Robotics",
      "headline": "Machines are learning to walk.",
      "summary": "Logistics pilots signal a shift from demo to production within eighteen months."
    },
    "classification": {
      "domain": "Robotics",
      "tags": [],
      "interest": "robotics"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 478,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "+752%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "+3%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 59,
      "velocity": 378,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Expect selective enterprise rollouts in logistics before consumer adoption. The winners will pair hardware reliability with software that learns from deployment data.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "robotics",
        "autonomous-systems",
        "semiconductor-supply-chain"
      ],
      "relatedCompanies": [
        "Tesla",
        "Figure AI",
        "Boston Dynamics",
        "Agility Robotics"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "entrepreneur",
        "investor"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "robotics"
      ]
    },
    "presentation": {
      "featured": true,
      "narrative": "Enterprise Growth",
      "sparkline": [
        48,
        52,
        54,
        58,
        62,
        66,
        72,
        76,
        79,
        82,
        84
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Bipedal robots are crossing from laboratory curiosity to warehouse pilot. Labor shortages and falling actuator costs make deployment economics plausible for the first time."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "quantum-computing",
      "slug": "quantum-computing",
      "title": "Quantum Computing",
      "headline": "Quantum is leaving the lab.",
      "summary": "Error correction progress opens problems classical systems may never solve."
    },
    "classification": {
      "domain": "Quantum",
      "tags": [],
      "interest": "quantum-computing"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 612,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion",
          "delta": "-40%"
        },
        {
          "type": "arxiv",
          "label": "Research Publications"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-35%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 39,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Near-term value will concentrate in simulation and cryptography research. Commercial advantage remains years away, but preparation windows are open now.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "cybersecurity",
        "cuda",
        "biotechnology"
      ],
      "relatedCompanies": [
        "IBM",
        "Google",
        "IonQ",
        "Microsoft"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "investor",
        "entrepreneur",
        "student"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "quantum-computing"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Research Breakthrough",
      "sparkline": [
        44,
        48,
        52,
        55,
        60,
        64,
        68,
        72,
        76,
        79,
        82
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Error correction milestones are shifting quantum from theoretical advantage to investable roadmap. Capital is arriving before most enterprises have assigned an owner."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "robotics",
      "slug": "robotics",
      "title": "Robotics",
      "headline": "Factories are hiring robots first.",
      "summary": "Unit economics crossed the threshold where automation beats rehiring at scale."
    },
    "classification": {
      "domain": "Robotics",
      "tags": [],
      "interest": "robotics"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 530,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "+752%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "+3%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 59,
      "velocity": 378,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Industrial robotics will grow fastest in markets with wage pressure and energy volatility. Software margins will exceed hardware margins within the decade.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "humanoid-robotics",
        "autonomous-systems",
        "cuda"
      ],
      "relatedCompanies": [
        "ABB",
        "Fanuc",
        "Tesla",
        "Amazon"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "entrepreneur",
        "investor"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "robotics"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Enterprise Growth",
      "sparkline": [
        50,
        52,
        55,
        58,
        62,
        65,
        68,
        72,
        74,
        77,
        79
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Factory automation economics now favor robots over rehiring in several regions. Manufacturers are standardizing on platforms that integrate vision, control, and fleet software."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "autonomous-systems",
      "slug": "autonomous-systems",
      "title": "Autonomous Systems",
      "headline": "Autonomy spreads beyond vehicles.",
      "summary": "Drones, warehouses, and maritime stacks share the same perception breakthroughs."
    },
    "classification": {
      "domain": "Autonomy",
      "tags": [],
      "interest": "robotics"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 456,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "+752%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "+3%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 59,
      "velocity": 378,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Regulatory clarity in key markets will unlock capital faster than technical progress. Operators with safety data will compound advantage.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "robotics",
        "cybersecurity",
        "cloud-infrastructure"
      ],
      "relatedCompanies": [
        "Waymo",
        "Tesla",
        "Amazon",
        "Anduril"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "entrepreneur",
        "investor"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "robotics"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Enterprise Growth",
      "sparkline": [
        46,
        50,
        52,
        56,
        58,
        62,
        65,
        68,
        71,
        74,
        76
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Autonomy is migrating from vehicles to warehouses, ports, and airspace. Shared perception stacks mean breakthroughs in one domain accelerate others."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "cybersecurity",
      "slug": "cybersecurity",
      "title": "Cybersecurity",
      "headline": "Defense must outpace AI offense.",
      "summary": "Threat models rewritten by generative attacks demand new architecture now."
    },
    "classification": {
      "domain": "Cybersecurity",
      "tags": [],
      "interest": "cybersecurity"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 422,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "+177%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-10%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 57,
      "velocity": 84,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Defense spending will shift toward continuous verification and identity-first architecture. Reactive tooling loses share to systems that model attacker behavior.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "agentic-ai",
        "cloud-infrastructure",
        "quantum-computing"
      ],
      "relatedCompanies": [
        "CrowdStrike",
        "Microsoft",
        "Palo Alto Networks",
        "Google"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "entrepreneur",
        "investor",
        "student"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "cybersecurity"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Rapid Adoption",
      "sparkline": [
        58,
        60,
        62,
        64,
        66,
        68,
        69,
        71,
        72,
        73,
        74
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Generative attacks are rewriting threat models faster than legacy defenses adapt. Boards are treating AI-native security as mandatory, not optional."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "cloud-infrastructure",
      "slug": "cloud-infrastructure",
      "title": "Cloud Infrastructure",
      "headline": "Inference is the new cloud war.",
      "summary": "Hyperscalers compete on latency and cost per token, not raw storage."
    },
    "classification": {
      "domain": "Cloud & Compute",
      "tags": [],
      "interest": "cloud-computing"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 398,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "-45%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "+12%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 45,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Multi-cloud inference orchestration will become standard for enterprises avoiding vendor lock-in. Price competition intensifies as utilization rates climb.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "cuda",
        "agentic-ai",
        "cybersecurity"
      ],
      "relatedCompanies": [
        "Amazon",
        "Microsoft",
        "Google",
        "Oracle"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "entrepreneur",
        "investor"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "cloud-computing"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Infrastructure Expansion",
      "sparkline": [
        54,
        56,
        58,
        60,
        62,
        64,
        66,
        68,
        69,
        71,
        72
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Hyperscalers are competing on inference latency and cost per token. Cloud strategy is now AI strategy, and procurement cycles are shortening."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "biotechnology",
      "slug": "biotechnology",
      "title": "Biotechnology",
      "headline": "Drug discovery timelines are collapsing.",
      "summary": "AI-designed molecules reach trials in months, not years. Pipelines are rewiring."
    },
    "classification": {
      "domain": "Life Sciences",
      "tags": [],
      "interest": "biotechnology"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 341,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "-30%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-3%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 39,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Regulatory frameworks will adapt to AI-assisted trials, but unevenly across regions. Early movers gain compound data advantages in target identification.",
      "forecastConfidence": "low"
    },
    "relationships": {
      "relatedSignals": [
        "quantum-computing",
        "fusion-energy",
        "agentic-ai"
      ],
      "relatedCompanies": [
        "DeepMind",
        "Recursion",
        "Moderna",
        "Roche"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "investor",
        "entrepreneur",
        "student"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "biotechnology"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Research Breakthrough",
      "sparkline": [
        48,
        50,
        52,
        54,
        56,
        58,
        60,
        62,
        64,
        66,
        68
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "AI-designed molecules are reaching trials in months rather than years. Pharmaceutical pipelines are being restructured around computational discovery teams."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "spatial-computing",
      "slug": "spatial-computing",
      "title": "Spatial Computing",
      "headline": "Enterprise is adopting mixed reality.",
      "summary": "Training and design use cases prove ROI beyond consumer hype cycles."
    },
    "classification": {
      "domain": "Artificial Intelligence",
      "tags": [],
      "interest": "artificial-intelligence"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 245,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-9%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 50,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "B2B adoption will lead consumer markets for several years. Platforms that integrate with existing CAD and LMS tools will capture durable share.",
      "forecastConfidence": "low"
    },
    "relationships": {
      "relatedSignals": [
        "robotics",
        "autonomous-systems",
        "cloud-infrastructure"
      ],
      "relatedCompanies": [
        "Apple",
        "Microsoft",
        "Meta",
        "Magic Leap"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "entrepreneur",
        "investor"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "artificial-intelligence"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Consumer Acceleration",
      "sparkline": [
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        59,
        60,
        61
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Enterprise training and design workflows are proving mixed reality ROI where consumer adoption stalled. Hardware comfort and software maturity are aligning."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "fusion-energy",
      "slug": "fusion-energy",
      "title": "Fusion Energy",
      "headline": "Fusion funding is reaching escape velocity.",
      "summary": "Net gain milestones pull private capital toward commercial timelines once deemed distant."
    },
    "classification": {
      "domain": "Energy",
      "tags": [],
      "interest": "energy"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 192,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "-41%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-1%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 44,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Commercial fusion remains distant, but grid-adjacent applications may arrive sooner than consensus expects. Policy support will determine regional winners.",
      "forecastConfidence": "low"
    },
    "relationships": {
      "relatedSignals": [
        "semiconductor-supply-chain",
        "biotechnology",
        "robotics"
      ],
      "relatedCompanies": [
        "Commonwealth Fusion",
        "Helion",
        "TAE Technologies",
        "Google"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "investor",
        "entrepreneur"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "energy"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Research Breakthrough",
      "sparkline": [
        46,
        48,
        49,
        50,
        52,
        53,
        54,
        55,
        56,
        57,
        58
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Net energy gain milestones are pulling private capital into timelines once considered science fiction. Energy security concerns amplify every breakthrough announcement."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "ai-manufacturing",
      "slug": "ai-manufacturing",
      "title": "AI-Driven Manufacturing",
      "headline": "Factories are becoming self-optimizing.",
      "summary": "Industrial AI links vision, control, and supply data into plants that tune themselves."
    },
    "classification": {
      "domain": "Manufacturing",
      "tags": [],
      "interest": "manufacturing"
    },
    "geography": {
      "primaryRegion": "india",
      "secondaryRegions": [
        "india",
        "china",
        "southeast-asia",
        "africa",
        "latin-america"
      ],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 388,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "-100%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-2%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 45,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Adoption leads in regions with wage pressure and new capacity. Software-defined plants will out-margin fixed automation within the decade.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "robotics",
        "semiconductor-supply-chain",
        "autonomous-systems"
      ],
      "relatedCompanies": [
        "Siemens",
        "Foxconn",
        "Bosch",
        "GE"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "entrepreneur",
        "investor"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [
        "india",
        "china",
        "southeast-asia",
        "africa",
        "latin-america"
      ],
      "recommendedInterests": [
        "manufacturing"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Enterprise Growth",
      "sparkline": [
        50,
        52,
        55,
        57,
        60,
        62,
        65,
        67,
        68,
        70,
        71
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Manufacturers are wiring AI into the plant floor, turning fixed production lines into systems that adapt to demand, defects, and disruption in real time. The edge now goes to operators who own their process data."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "ai-financial-services",
      "slug": "ai-financial-services",
      "title": "AI in Financial Services",
      "headline": "Underwriting is being rebuilt on models.",
      "summary": "Credit, fraud, and risk pipelines are moving from fixed rules to learned systems."
    },
    "classification": {
      "domain": "Finance",
      "tags": [],
      "interest": "finance"
    },
    "geography": {
      "primaryRegion": "north-america",
      "secondaryRegions": [
        "north-america",
        "europe",
        "india",
        "africa"
      ],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 402,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-10%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 50,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Regulation shapes pace more than technology. Firms that pair model-risk management with speed take share from incumbents.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "cybersecurity",
        "cloud-infrastructure",
        "agentic-ai"
      ],
      "relatedCompanies": [
        "JPMorgan",
        "Stripe",
        "Visa",
        "Revolut"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "investor",
        "entrepreneur"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [
        "north-america",
        "europe",
        "india",
        "africa"
      ],
      "recommendedInterests": [
        "finance"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Rapid Adoption",
      "sparkline": [
        55,
        57,
        59,
        61,
        63,
        65,
        67,
        69,
        70,
        72,
        73
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Banks and fintechs are replacing static rules with models across credit, fraud, and compliance. The advantage accrues to institutions with clean proprietary data and the governance to deploy models safely."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "ai-clinical-diagnostics",
      "slug": "ai-clinical-diagnostics",
      "title": "AI Clinical Diagnostics",
      "headline": "Diagnosis is getting a second reader.",
      "summary": "Imaging and pathology models are reaching specialist parity on narrow tasks."
    },
    "classification": {
      "domain": "Healthcare",
      "tags": [],
      "interest": "healthcare"
    },
    "geography": {
      "primaryRegion": "north-america",
      "secondaryRegions": [
        "north-america",
        "europe",
        "india",
        "africa"
      ],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 356,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-1%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 47,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Reimbursement and liability frameworks gate scale. Markets with specialist shortages adopt fastest.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "biotechnology",
        "agentic-ai",
        "cloud-infrastructure"
      ],
      "relatedCompanies": [
        "Google",
        "Siemens Healthineers",
        "Nvidia",
        "Tempus"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "student",
        "investor"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [
        "north-america",
        "europe",
        "india",
        "africa"
      ],
      "recommendedInterests": [
        "healthcare"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Research Breakthrough",
      "sparkline": [
        54,
        56,
        58,
        60,
        62,
        63,
        65,
        67,
        68,
        69,
        70
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "AI diagnostic tools are clearing regulators and entering clinical workflows, easing specialist shortages. Health systems that integrate them into care pathways — not just pilots — capture the outcomes and the savings."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "venture-capital-flows",
      "slug": "venture-capital-flows",
      "title": "Venture Capital Flows",
      "headline": "Capital is concentrating in AI infrastructure.",
      "summary": "Funding is narrowing to fewer, larger bets on compute, agents, and applied AI."
    },
    "classification": {
      "domain": "Capital Markets",
      "tags": [],
      "interest": "venture-capital"
    },
    "geography": {
      "primaryRegion": "north-america",
      "secondaryRegions": [
        "north-america",
        "europe",
        "india",
        "southeast-asia"
      ],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 331,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        },
        {
          "type": "product-hunt",
          "label": "Product Launches",
          "delta": "-22%"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 46,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Concentration persists until rates ease or a breakout application broadens the field. Hubs with policy support retain share.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "agentic-ai",
        "cuda",
        "cloud-infrastructure"
      ],
      "relatedCompanies": [
        "Sequoia",
        "a16z",
        "Tiger Global",
        "SoftBank"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "investor",
        "entrepreneur"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [
        "north-america",
        "europe",
        "india",
        "southeast-asia"
      ],
      "recommendedInterests": [
        "venture-capital",
        "startups"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Infrastructure Expansion",
      "sparkline": [
        52,
        54,
        56,
        58,
        60,
        62,
        64,
        66,
        67,
        68,
        69
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Venture capital is consolidating around AI infrastructure and applied-AI platforms, thinning funding elsewhere. Founders and investors are repricing which categories can still raise — and at what velocity."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "computational-biochemistry",
      "slug": "computational-biochemistry",
      "title": "Computational Biochemistry",
      "headline": "Protein design is becoming programmable.",
      "summary": "Generative models are turning molecular design from search into specification."
    },
    "classification": {
      "domain": "Life Sciences",
      "tags": [],
      "interest": "biochemistry"
    },
    "geography": {
      "primaryRegion": "europe",
      "secondaryRegions": [
        "europe",
        "north-america",
        "india",
        "latin-america"
      ],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 274,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "-29%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-4%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 40,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Design tools commoditize; proprietary assays and data become the moat. AI labs and bench science partner to close the loop.",
      "forecastConfidence": "low"
    },
    "relationships": {
      "relatedSignals": [
        "biotechnology",
        "ai-clinical-diagnostics",
        "quantum-computing"
      ],
      "relatedCompanies": [
        "DeepMind",
        "Isomorphic Labs",
        "Genentech",
        "BASF"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "student",
        "investor",
        "entrepreneur"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [
        "europe",
        "north-america",
        "india",
        "latin-america"
      ],
      "recommendedInterests": [
        "biochemistry",
        "life-sciences"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Research Breakthrough",
      "sparkline": [
        50,
        52,
        54,
        56,
        58,
        60,
        61,
        63,
        64,
        65,
        66
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Structure prediction and generative chemistry are compressing the discovery loop — teams specify a target and design toward it. Wet-lab validation, not ideas, is now the bottleneck."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "ai-life-sciences",
      "slug": "ai-life-sciences",
      "title": "AI in Life Sciences",
      "headline": "Research is compounding on models.",
      "summary": "Literature, lab data, and trials are unified into models that propose the next experiment."
    },
    "classification": {
      "domain": "Life Sciences",
      "tags": [],
      "interest": "life-sciences"
    },
    "geography": {
      "primaryRegion": "north-america",
      "secondaryRegions": [
        "north-america",
        "europe",
        "india",
        "middle-east"
      ],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 258,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        },
        {
          "type": "product-hunt",
          "label": "Product Launches",
          "delta": "-33%"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 44,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Data interoperability and provenance decide winners. Expect consolidation around platforms that make evidence auditable.",
      "forecastConfidence": "low"
    },
    "relationships": {
      "relatedSignals": [
        "biotechnology",
        "ai-clinical-diagnostics",
        "computational-biochemistry"
      ],
      "relatedCompanies": [
        "Recursion",
        "Insitro",
        "Novartis",
        "AstraZeneca"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "student",
        "professional",
        "investor"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [
        "north-america",
        "europe",
        "india",
        "middle-east"
      ],
      "recommendedInterests": [
        "life-sciences",
        "healthcare"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Research Breakthrough",
      "sparkline": [
        48,
        50,
        52,
        54,
        56,
        57,
        59,
        60,
        62,
        63,
        64
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Life-science teams are layering AI over fragmented research and trial data to surface hypotheses and cut dead-end experiments. The advantage goes to institutions that can connect their data, not just collect it."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "generative-creative-tools",
      "slug": "generative-creative-tools",
      "title": "Generative Creative Tools",
      "headline": "Creative work is being reorganized.",
      "summary": "Image, video, and audio models are shifting craft from execution to direction."
    },
    "classification": {
      "domain": "Arts & Media",
      "tags": [],
      "interest": "arts"
    },
    "geography": {
      "primaryRegion": "north-america",
      "secondaryRegions": [
        "north-america",
        "europe",
        "latin-america",
        "southeast-asia"
      ],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 289,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "-100%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-11%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 41,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Provenance, licensing, and authorship rules shape the market more than model quality. Curation becomes the differentiator.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "agentic-ai",
        "spatial-computing",
        "cloud-infrastructure"
      ],
      "relatedCompanies": [
        "Adobe",
        "OpenAI",
        "Runway",
        "Canva"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "student",
        "entrepreneur"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [
        "north-america",
        "europe",
        "latin-america",
        "southeast-asia"
      ],
      "recommendedInterests": [
        "arts",
        "commerce"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Consumer Acceleration",
      "sparkline": [
        54,
        56,
        57,
        59,
        60,
        62,
        63,
        64,
        65,
        66,
        67
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Generative tools are collapsing production time for image, video, and audio, moving the scarce skill from execution to taste and direction. Studios and independents are renegotiating who owns the output — and the rights."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "ai-commerce",
      "slug": "ai-commerce",
      "title": "AI-Native Commerce",
      "headline": "Storefronts are becoming conversational.",
      "summary": "Discovery, pricing, and support are shifting from pages to agents."
    },
    "classification": {
      "domain": "Commerce",
      "tags": [],
      "interest": "commerce"
    },
    "geography": {
      "primaryRegion": "latin-america",
      "secondaryRegions": [
        "latin-america",
        "north-america",
        "southeast-asia",
        "india",
        "africa"
      ],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 312,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "-58%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "+0%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 42,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Platform agents intermediate more demand. Brands invest in first-party data and direct channels to avoid disintermediation.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "agentic-ai",
        "ai-financial-services",
        "cloud-infrastructure"
      ],
      "relatedCompanies": [
        "Amazon",
        "Shopify",
        "Mercado Libre",
        "Alibaba"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "entrepreneur",
        "student",
        "professional"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [
        "latin-america",
        "north-america",
        "southeast-asia",
        "india",
        "africa"
      ],
      "recommendedInterests": [
        "commerce",
        "startups"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Rapid Adoption",
      "sparkline": [
        55,
        57,
        58,
        60,
        61,
        63,
        64,
        65,
        66,
        67,
        68
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Retail is moving from search-and-browse to agent-led discovery, dynamic pricing, and automated support. Merchants with clean catalog and behavioral data adapt fastest; the rest cede the customer relationship to platforms."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  }
] as const;
export const GENERATED_AT = "2026-07-11T17:50:57.794Z";
