// Machine-generated by `npm run pipeline:signals`. Do not edit.
import type { Signal } from "@/lib/domain";

export const GENERATED_SIGNALS: readonly Signal[] = [
  {
    "identity": {
      "id": "agentic-ai",
      "slug": "agentic-ai",
      "title": "Agentic AI",
      "headline": "Software is becoming autonomous.",
      "summary": "Teams shipping agent workflows move faster. Those waiting risk falling behind within two quarters."
    },
    "classification": {
      "domain": "Artificial Intelligence",
      "tags": [],
      "interest": "artificial-intelligence"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 1248,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-9%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 50,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Over the next year, agent frameworks will become default infrastructure for software teams. Late adopters will compete on integration speed, not model access alone.",
      "forecastConfidence": "high"
    },
    "relationships": {
      "relatedSignals": [
        "cuda",
        "cloud-infrastructure",
        "cybersecurity",
        "autonomous-systems"
      ],
      "relatedCompanies": [
        "OpenAI",
        "Microsoft",
        "Google",
        "Anthropic"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "entrepreneur",
        "investor",
        "student"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "artificial-intelligence"
      ]
    },
    "presentation": {
      "featured": true,
      "narrative": "Rapid Adoption",
      "sparkline": [
        47,
        36,
        46,
        32,
        50
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Agentic systems are moving from demos to production workflows faster than most organizations can retool. The window to build internal capability is narrowing as incumbents embed autonomy into core products."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "cuda",
      "slug": "cuda",
      "title": "CUDA",
      "headline": "AI compute demand is accelerating.",
      "summary": "Every frontier model depends on GPU scale. Capacity now decides who ships first."
    },
    "classification": {
      "domain": "Cloud & Compute",
      "tags": [],
      "interest": "cloud-computing"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 982,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "-45%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "+12%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 45,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Inference demand will outpace training within eighteen months. Firms that secure long-term compute contracts now will ship features others cannot.",
      "forecastConfidence": "high"
    },
    "relationships": {
      "relatedSignals": [
        "agentic-ai",
        "semiconductor-supply-chain",
        "cloud-infrastructure"
      ],
      "relatedCompanies": [
        "NVIDIA",
        "Microsoft",
        "Google",
        "Amazon"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "entrepreneur",
        "investor"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "cloud-computing"
      ]
    },
    "presentation": {
      "featured": true,
      "narrative": "Infrastructure Expansion",
      "sparkline": [
        41,
        21,
        37,
        30,
        45
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "GPU compute is the binding constraint on AI progress. Every major model release intensifies competition for CUDA-class capacity and the talent to operate it."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "semiconductor-supply-chain",
      "slug": "semiconductor-supply-chain",
      "title": "Semiconductor Supply Chain",
      "headline": "Chip supply is now strategic power.",
      "summary": "Nations and firms race to secure advanced packaging before the next capacity crunch."
    },
    "classification": {
      "domain": "Supply Chain",
      "tags": [],
      "interest": "supply-chain"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 715,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "-50%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-5%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 42,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Regional diversification will accelerate through 2027. Companies without dual-source strategies face multi-quarter delays on every hardware roadmap.",
      "forecastConfidence": "high"
    },
    "relationships": {
      "relatedSignals": [
        "cuda",
        "quantum-computing",
        "robotics"
      ],
      "relatedCompanies": [
        "TSMC",
        "NVIDIA",
        "Intel",
        "Samsung"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "entrepreneur",
        "investor"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "supply-chain"
      ]
    },
    "presentation": {
      "featured": true,
      "narrative": "Infrastructure Expansion",
      "sparkline": [
        41,
        27,
        36,
        32,
        42
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Advanced packaging and geopolitical alignment now determine who can build frontier compute at scale. Supply security has become a board-level risk, not a procurement detail."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "humanoid-robotics",
      "slug": "humanoid-robotics",
      "title": "Humanoid Robotics",
      "headline": "Machines are learning to walk.",
      "summary": "Logistics pilots signal a shift from demo to production within eighteen months."
    },
    "classification": {
      "domain": "Robotics",
      "tags": [],
      "interest": "robotics"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 478,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "+752%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "+3%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 59,
      "velocity": 378,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Expect selective enterprise rollouts in logistics before consumer adoption. The winners will pair hardware reliability with software that learns from deployment data.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "robotics",
        "autonomous-systems",
        "semiconductor-supply-chain"
      ],
      "relatedCompanies": [
        "Tesla",
        "Figure AI",
        "Boston Dynamics",
        "Agility Robotics"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "entrepreneur",
        "investor"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "robotics"
      ]
    },
    "presentation": {
      "featured": true,
      "narrative": "Enterprise Growth",
      "sparkline": [
        51,
        49,
        58,
        42,
        59
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Bipedal robots are crossing from laboratory curiosity to warehouse pilot. Labor shortages and falling actuator costs make deployment economics plausible for the first time."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "quantum-computing",
      "slug": "quantum-computing",
      "title": "Quantum Computing",
      "headline": "Quantum is leaving the lab.",
      "summary": "Error correction progress opens problems classical systems may never solve."
    },
    "classification": {
      "domain": "Quantum",
      "tags": [],
      "interest": "quantum-computing"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 612,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion",
          "delta": "-40%"
        },
        {
          "type": "arxiv",
          "label": "Research Publications"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-35%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 39,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Near-term value will concentrate in simulation and cryptography research. Commercial advantage remains years away, but preparation windows are open now.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "cybersecurity",
        "cuda",
        "biotechnology"
      ],
      "relatedCompanies": [
        "IBM",
        "Google",
        "IonQ",
        "Microsoft"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "investor",
        "entrepreneur",
        "student"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "quantum-computing"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Research Breakthrough",
      "sparkline": [
        63,
        20,
        53,
        29,
        39
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Error correction milestones are shifting quantum from theoretical advantage to investable roadmap. Capital is arriving before most enterprises have assigned an owner."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "robotics",
      "slug": "robotics",
      "title": "Robotics",
      "headline": "Factories are hiring robots first.",
      "summary": "Unit economics crossed the threshold where automation beats rehiring at scale."
    },
    "classification": {
      "domain": "Robotics",
      "tags": [],
      "interest": "robotics"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 530,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "+752%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "+3%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 59,
      "velocity": 378,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Industrial robotics will grow fastest in markets with wage pressure and energy volatility. Software margins will exceed hardware margins within the decade.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "humanoid-robotics",
        "autonomous-systems",
        "cuda"
      ],
      "relatedCompanies": [
        "ABB",
        "Fanuc",
        "Tesla",
        "Amazon"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "entrepreneur",
        "investor"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "robotics"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Enterprise Growth",
      "sparkline": [
        51,
        49,
        58,
        42,
        59
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Factory automation economics now favor robots over rehiring in several regions. Manufacturers are standardizing on platforms that integrate vision, control, and fleet software."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "autonomous-systems",
      "slug": "autonomous-systems",
      "title": "Autonomous Systems",
      "headline": "Autonomy spreads beyond vehicles.",
      "summary": "Drones, warehouses, and maritime stacks share the same perception breakthroughs."
    },
    "classification": {
      "domain": "Autonomy",
      "tags": [],
      "interest": "robotics"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 456,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "+752%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "+3%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 59,
      "velocity": 378,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Regulatory clarity in key markets will unlock capital faster than technical progress. Operators with safety data will compound advantage.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "robotics",
        "cybersecurity",
        "cloud-infrastructure"
      ],
      "relatedCompanies": [
        "Waymo",
        "Tesla",
        "Amazon",
        "Anduril"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "entrepreneur",
        "investor"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "robotics"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Enterprise Growth",
      "sparkline": [
        51,
        49,
        58,
        42,
        59
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Autonomy is migrating from vehicles to warehouses, ports, and airspace. Shared perception stacks mean breakthroughs in one domain accelerate others."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "cybersecurity",
      "slug": "cybersecurity",
      "title": "Cybersecurity",
      "headline": "Defense must outpace AI offense.",
      "summary": "Threat models rewritten by generative attacks demand new architecture now."
    },
    "classification": {
      "domain": "Cybersecurity",
      "tags": [],
      "interest": "cybersecurity"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 422,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "+177%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-10%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 57,
      "velocity": 84,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Defense spending will shift toward continuous verification and identity-first architecture. Reactive tooling loses share to systems that model attacker behavior.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "agentic-ai",
        "cloud-infrastructure",
        "quantum-computing"
      ],
      "relatedCompanies": [
        "CrowdStrike",
        "Microsoft",
        "Palo Alto Networks",
        "Google"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "entrepreneur",
        "investor",
        "student"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "cybersecurity"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Rapid Adoption",
      "sparkline": [
        62,
        42,
        48,
        41,
        57
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Generative attacks are rewriting threat models faster than legacy defenses adapt. Boards are treating AI-native security as mandatory, not optional."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "cloud-infrastructure",
      "slug": "cloud-infrastructure",
      "title": "Cloud Infrastructure",
      "headline": "Inference is the new cloud war.",
      "summary": "Hyperscalers compete on latency and cost per token, not raw storage."
    },
    "classification": {
      "domain": "Cloud & Compute",
      "tags": [],
      "interest": "cloud-computing"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 398,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "-45%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "+12%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 45,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Multi-cloud inference orchestration will become standard for enterprises avoiding vendor lock-in. Price competition intensifies as utilization rates climb.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "cuda",
        "agentic-ai",
        "cybersecurity"
      ],
      "relatedCompanies": [
        "Amazon",
        "Microsoft",
        "Google",
        "Oracle"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "entrepreneur",
        "investor"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "cloud-computing"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Infrastructure Expansion",
      "sparkline": [
        41,
        21,
        37,
        30,
        45
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Hyperscalers are competing on inference latency and cost per token. Cloud strategy is now AI strategy, and procurement cycles are shortening."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "biotechnology",
      "slug": "biotechnology",
      "title": "Biotechnology",
      "headline": "Gene editing is reaching the clinic.",
      "summary": "Approved CRISPR and cell therapies move from single trials into standard treatment pipelines."
    },
    "classification": {
      "domain": "Life Sciences",
      "tags": [],
      "interest": "biotechnology"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 341,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "-30%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-3%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 39,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Payer coverage and one-time-cure pricing models set the pace. Regions that solve reimbursement and cold-chain delivery adopt first; others wait for cost curves to fall.",
      "forecastConfidence": "low"
    },
    "relationships": {
      "relatedSignals": [
        "computational-biochemistry",
        "ai-life-sciences",
        "ai-clinical-diagnostics"
      ],
      "relatedCompanies": [
        "Vertex",
        "CRISPR Therapeutics",
        "Novartis",
        "Regeneron"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "investor",
        "entrepreneur",
        "student"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "biotechnology"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Research Breakthrough",
      "sparkline": [
        40,
        26,
        32,
        33,
        39
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "The first gene-editing therapies have cleared regulators and are entering care pathways for sickle-cell and inherited disease, while cell therapies broaden beyond oncology. Manufacturing scale and durable pricing — not the underlying biology — now decide which programs reach patients."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "spatial-computing",
      "slug": "spatial-computing",
      "title": "Spatial Computing",
      "headline": "Enterprise is adopting mixed reality.",
      "summary": "Training and design use cases prove ROI beyond consumer hype cycles."
    },
    "classification": {
      "domain": "Artificial Intelligence",
      "tags": [],
      "interest": "artificial-intelligence"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 245,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-9%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 50,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "B2B adoption will lead consumer markets for several years. Platforms that integrate with existing CAD and LMS tools will capture durable share.",
      "forecastConfidence": "low"
    },
    "relationships": {
      "relatedSignals": [
        "robotics",
        "autonomous-systems",
        "cloud-infrastructure"
      ],
      "relatedCompanies": [
        "Apple",
        "Microsoft",
        "Meta",
        "Magic Leap"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "entrepreneur",
        "investor"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "artificial-intelligence"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Consumer Acceleration",
      "sparkline": [
        47,
        36,
        46,
        32,
        50
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Enterprise training and design workflows are proving mixed reality ROI where consumer adoption stalled. Hardware comfort and software maturity are aligning."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "fusion-energy",
      "slug": "fusion-energy",
      "title": "Fusion Energy",
      "headline": "Fusion funding is reaching escape velocity.",
      "summary": "Net gain milestones pull private capital toward commercial timelines once deemed distant."
    },
    "classification": {
      "domain": "Energy",
      "tags": [],
      "interest": "energy"
    },
    "geography": {
      "secondaryRegions": [],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 192,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "-41%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-1%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 44,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Commercial fusion remains distant, but grid-adjacent applications may arrive sooner than consensus expects. Policy support will determine regional winners.",
      "forecastConfidence": "low"
    },
    "relationships": {
      "relatedSignals": [
        "semiconductor-supply-chain",
        "biotechnology",
        "robotics"
      ],
      "relatedCompanies": [
        "Commonwealth Fusion",
        "Helion",
        "TAE Technologies",
        "Google"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "investor",
        "entrepreneur"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [],
      "recommendedInterests": [
        "energy"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Research Breakthrough",
      "sparkline": [
        27,
        21,
        39,
        33,
        44
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Net energy gain milestones are pulling private capital into timelines once considered science fiction. Energy security concerns amplify every breakthrough announcement."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "ai-manufacturing",
      "slug": "ai-manufacturing",
      "title": "Advanced Manufacturing",
      "headline": "Production is reshoring and automating.",
      "summary": "Supply-chain security and robotics pull factories closer to demand."
    },
    "classification": {
      "domain": "Manufacturing",
      "tags": [],
      "interest": "manufacturing"
    },
    "geography": {
      "primaryRegion": "india",
      "secondaryRegions": [
        "india",
        "china",
        "southeast-asia",
        "africa",
        "latin-america"
      ],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 388,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "-100%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-2%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 45,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Adoption leads where wages, subsidies, and energy costs align. Flexible, software-defined plants out-margin fixed automation within the decade.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "robotics",
        "semiconductor-supply-chain",
        "autonomous-systems"
      ],
      "relatedCompanies": [
        "Siemens",
        "Foxconn",
        "Bosch",
        "GE"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "entrepreneur",
        "investor"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [
        "india",
        "china",
        "southeast-asia",
        "africa",
        "latin-america"
      ],
      "recommendedInterests": [
        "manufacturing"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Enterprise Growth",
      "sparkline": [
        48,
        22,
        50,
        33,
        45
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Manufacturers are relocating capacity closer to end markets and rebuilding lines around robotics and flexible tooling, driven by supply-chain risk and industrial policy. The advantage shifts to operators who can retool quickly and secure their inputs."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "ai-financial-services",
      "slug": "ai-financial-services",
      "title": "Financial Markets",
      "headline": "Private credit is reshaping lending.",
      "summary": "Capital shifts from banks to private funds as rates reset risk and returns."
    },
    "classification": {
      "domain": "Finance",
      "tags": [],
      "interest": "finance"
    },
    "geography": {
      "primaryRegion": "north-america",
      "secondaryRegions": [
        "north-america",
        "europe",
        "india",
        "africa"
      ],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 402,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-10%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 50,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Rate paths and regulation shape the pace more than any single product. Firms that pair balance-sheet strength with distribution take share from incumbents.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "venture-capital-flows",
        "ai-commerce",
        "cybersecurity"
      ],
      "relatedCompanies": [
        "JPMorgan",
        "Blackstone",
        "Apollo",
        "Visa"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "investor",
        "entrepreneur"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [
        "north-america",
        "europe",
        "india",
        "africa"
      ],
      "recommendedInterests": [
        "finance"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Rapid Adoption",
      "sparkline": [
        58,
        36,
        42,
        40,
        50
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Private credit funds are taking lending share from banks while higher-for-longer rates reprice risk across the system. Institutions with durable deposits and disciplined underwriting gain; those reliant on cheap funding retreat."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "ai-clinical-diagnostics",
      "slug": "ai-clinical-diagnostics",
      "title": "Metabolic Medicine",
      "headline": "Obesity drugs are reshaping healthcare economics.",
      "summary": "GLP-1 therapies expand from diabetes into chronic-disease care, straining supply and budgets."
    },
    "classification": {
      "domain": "Healthcare",
      "tags": [],
      "interest": "healthcare"
    },
    "geography": {
      "primaryRegion": "north-america",
      "secondaryRegions": [
        "north-america",
        "europe",
        "india",
        "africa"
      ],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 356,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-1%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 47,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Coverage decisions and biosimilar timelines determine access. Markets with public reimbursement or local manufacturing widen availability first.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "biotechnology",
        "ai-life-sciences",
        "computational-biochemistry"
      ],
      "relatedCompanies": [
        "Novo Nordisk",
        "Eli Lilly",
        "Pfizer",
        "Roche"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "professional",
        "student",
        "investor"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [
        "north-america",
        "europe",
        "india",
        "africa"
      ],
      "recommendedInterests": [
        "healthcare"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Rapid Adoption",
      "sparkline": [
        41,
        41,
        47,
        41,
        47
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "GLP-1 medicines are spreading from diabetes into obesity, cardiovascular, and other chronic indications, shifting demand and drug budgets faster than health systems planned. Supply, coverage rules, and adherence — not efficacy — now govern who gets treated."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "venture-capital-flows",
      "slug": "venture-capital-flows",
      "title": "Venture Capital Flows",
      "headline": "Venture funding is repricing risk.",
      "summary": "Higher rates and scarce exits concentrate capital and lengthen fundraising."
    },
    "classification": {
      "domain": "Capital Markets",
      "tags": [],
      "interest": "venture-capital"
    },
    "geography": {
      "primaryRegion": "north-america",
      "secondaryRegions": [
        "north-america",
        "europe",
        "india",
        "southeast-asia"
      ],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 331,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        },
        {
          "type": "product-hunt",
          "label": "Product Launches",
          "delta": "-22%"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 46,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Exit windows and rate cuts set the recovery pace. Hubs with deep talent and policy support retain share as capital turns selective.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "ai-financial-services",
        "ai-commerce",
        "biotechnology"
      ],
      "relatedCompanies": [
        "Sequoia",
        "a16z",
        "Tiger Global",
        "SoftBank"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "investor",
        "entrepreneur"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [
        "north-america",
        "europe",
        "india",
        "southeast-asia"
      ],
      "recommendedInterests": [
        "venture-capital",
        "startups"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Market Shift",
      "sparkline": [
        51,
        36,
        38,
        42,
        46
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Venture capital is adjusting to higher rates, fewer IPOs, and slower distributions, concentrating capital in fewer firms and later stages. Founders and funds are repricing which categories can raise — and how long the runway must be."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "computational-biochemistry",
      "slug": "computational-biochemistry",
      "title": "Protein Engineering",
      "headline": "Designed proteins are entering industry.",
      "summary": "Engineered enzymes and de novo proteins move from journals into materials, food, and medicine."
    },
    "classification": {
      "domain": "Life Sciences",
      "tags": [],
      "interest": "biochemistry"
    },
    "geography": {
      "primaryRegion": "europe",
      "secondaryRegions": [
        "europe",
        "north-america",
        "india",
        "latin-america"
      ],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 274,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "-29%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-4%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 40,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Proprietary assays and fermentation capacity become the moat as design methods spread. Chemistry and bench science partner to close the loop.",
      "forecastConfidence": "low"
    },
    "relationships": {
      "relatedSignals": [
        "biotechnology",
        "ai-life-sciences",
        "ai-clinical-diagnostics"
      ],
      "relatedCompanies": [
        "Genentech",
        "Novozymes",
        "BASF",
        "Ginkgo Bioworks"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "student",
        "investor",
        "entrepreneur"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [
        "europe",
        "north-america",
        "india",
        "latin-america"
      ],
      "recommendedInterests": [
        "biochemistry",
        "life-sciences"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Research Breakthrough",
      "sparkline": [
        32,
        28,
        51,
        32,
        40
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Custom-designed enzymes and de novo proteins are crossing from academic milestones into industrial catalysis, sustainable materials, and therapeutics. Wet-lab validation and scale-up, not design ideas, now set the pace."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "ai-life-sciences",
      "slug": "ai-life-sciences",
      "title": "Life Sciences Research",
      "headline": "Single-cell biology is redrawing disease maps.",
      "summary": "Spatial and single-cell techniques resolve tissues cell by cell, changing how disease is defined."
    },
    "classification": {
      "domain": "Life Sciences",
      "tags": [],
      "interest": "life-sciences"
    },
    "geography": {
      "primaryRegion": "north-america",
      "secondaryRegions": [
        "north-america",
        "europe",
        "india",
        "middle-east"
      ],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 258,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        },
        {
          "type": "product-hunt",
          "label": "Product Launches",
          "delta": "-33%"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 44,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Standardized protocols and shared reference atlases decide which findings translate. Institutions that pool data and reagents compound their advantage.",
      "forecastConfidence": "low"
    },
    "relationships": {
      "relatedSignals": [
        "biotechnology",
        "computational-biochemistry",
        "ai-clinical-diagnostics"
      ],
      "relatedCompanies": [
        "10x Genomics",
        "Illumina",
        "Genentech",
        "AstraZeneca"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "student",
        "professional",
        "investor"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [
        "north-america",
        "europe",
        "india",
        "middle-east"
      ],
      "recommendedInterests": [
        "life-sciences",
        "healthcare"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Research Breakthrough",
      "sparkline": [
        50,
        35,
        47,
        39,
        44
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Spatial and single-cell methods let researchers read gene activity one cell at a time, redrawing the maps of cancer, immunity, and neurological disease. The bottleneck has moved from generating data to interpreting and reproducing it."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "generative-creative-tools",
      "slug": "generative-creative-tools",
      "title": "Creative Economy",
      "headline": "Creators are becoming media companies.",
      "summary": "Direct monetization and live experiences reshape who captures cultural value."
    },
    "classification": {
      "domain": "Arts & Media",
      "tags": [],
      "interest": "arts"
    },
    "geography": {
      "primaryRegion": "north-america",
      "secondaryRegions": [
        "north-america",
        "europe",
        "latin-america",
        "southeast-asia"
      ],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 289,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "-100%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "-11%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 41,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "Platform economics and rights ownership decide who keeps the margin. Creators who own their audience and catalog outlast algorithm cycles.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "ai-commerce",
        "venture-capital-flows",
        "ai-financial-services"
      ],
      "relatedCompanies": [
        "Spotify",
        "Patreon",
        "Live Nation",
        "Sotheby's"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "student",
        "entrepreneur"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [
        "north-america",
        "europe",
        "latin-america",
        "southeast-asia"
      ],
      "recommendedInterests": [
        "arts",
        "commerce"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Consumer Acceleration",
      "sparkline": [
        35,
        22,
        37,
        32,
        41
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Independent artists and creators are building direct-to-audience businesses — subscriptions, live events, licensing — capturing value that once flowed to labels, galleries, and studios. Distribution reach no longer guarantees the audience relationship."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  },
  {
    "identity": {
      "id": "ai-commerce",
      "slug": "ai-commerce",
      "title": "Retail Reinvention",
      "headline": "Retail media is becoming the margin.",
      "summary": "Ad networks, quick commerce, and first-party data reshape where retailers earn."
    },
    "classification": {
      "domain": "Commerce",
      "tags": [],
      "interest": "commerce"
    },
    "geography": {
      "primaryRegion": "latin-america",
      "secondaryRegions": [
        "latin-america",
        "north-america",
        "southeast-asia",
        "india",
        "africa"
      ],
      "globalImpact": true
    },
    "evidence": {
      "evidenceCount": 312,
      "sources": [
        {
          "type": "hacker-news",
          "label": "Developer Discussion"
        },
        {
          "type": "arxiv",
          "label": "Research Publications",
          "delta": "-58%"
        },
        {
          "type": "wikipedia",
          "label": "Public Attention",
          "delta": "+0%"
        },
        {
          "type": "github",
          "label": "GitHub Activity"
        }
      ],
      "lastObserved": "2026-07-11T16:55:19.414Z",
      "freshness": "live",
      "confidence": "high"
    },
    "momentum": {
      "momentumScore": 42,
      "velocity": 0,
      "trajectory": "emerging"
    },
    "forecast": {
      "forecast": "First-party data and last-mile density decide winners. Merchants that own the customer relationship resist platform disintermediation.",
      "forecastConfidence": "medium"
    },
    "relationships": {
      "relatedSignals": [
        "ai-financial-services",
        "generative-creative-tools",
        "venture-capital-flows"
      ],
      "relatedCompanies": [
        "Amazon",
        "Shopify",
        "Mercado Libre",
        "Alibaba"
      ],
      "relatedTechnologies": [],
      "relatedIndustries": []
    },
    "personalization": {
      "recommendedRoles": [
        "entrepreneur",
        "student",
        "professional"
      ],
      "recommendedIndustries": [],
      "recommendedRegions": [
        "latin-america",
        "north-america",
        "southeast-asia",
        "india",
        "africa"
      ],
      "recommendedInterests": [
        "commerce",
        "startups"
      ]
    },
    "presentation": {
      "featured": false,
      "narrative": "Rapid Adoption",
      "sparkline": [
        66,
        27,
        40,
        30,
        42
      ]
    },
    "reading": {
      "estimatedReadTime": 1,
      "brief": "Retailers are building high-margin advertising networks on their shopper data while quick commerce compresses delivery windows. Profit is shifting from selling goods to monetizing attention and logistics."
    },
    "versioning": {
      "createdAt": "2026-07-08T00:00:00.000Z",
      "updatedAt": "2026-07-11T16:55:19.414Z",
      "revision": 2,
      "status": "active"
    }
  }
] as const;
export const GENERATED_AT = "2026-07-13T18:57:59.444Z";
