import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import type {
  BriefingRecord,
  JobRecord,
  MetaRecord,
  RecommendationRecord,
  SkillRecord,
} from "@/lib/data/schemas";
import type { GenerateBriefingResult } from "@/lib/pipeline/generate/briefing";

const DATA_ROOT = path.join(process.cwd(), "data");
const BRIEFINGS_DIR = path.join(DATA_ROOT, "briefings");
const REGISTRY_PATH = path.join(
  process.cwd(),
  "lib",
  "data",
  "briefings-registry.ts"
);

async function writeJson(filePath: string, data: unknown): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, `${JSON.stringify(data, null, 2)}\n`, "utf8");
}

export async function writeBriefingArtifacts(
  result: GenerateBriefingResult
): Promise<{
  briefingPath: string;
  metaPath: string;
  registryPath: string;
}> {
  const briefingPath = path.join(BRIEFINGS_DIR, result.briefingFile);
  const metaPath = path.join(DATA_ROOT, "meta.json");

  await writeJson(briefingPath, result.briefing);
  await writeJson(metaPath, result.meta);
  await writeJson(path.join(DATA_ROOT, "skills.json"), { skills: result.skills });
  await writeJson(path.join(DATA_ROOT, "jobs.json"), { jobs: result.jobs });
  await writeJson(path.join(DATA_ROOT, "recommendations.json"), {
    recommendations: result.recommendations,
  });

  await syncBriefingsRegistry();

  return {
    briefingPath,
    metaPath,
    registryPath: REGISTRY_PATH,
  };
}

export async function syncBriefingsRegistry(): Promise<void> {
  await mkdir(BRIEFINGS_DIR, { recursive: true });
  const files = (await readdir(BRIEFINGS_DIR))
    .filter((name) => name.endsWith(".json"))
    .sort();

  const imports = files
    .map((file) => {
      const varName = file.replace(".json", "").replace(/-/g, "_");
      return `import briefing_${varName} from "@/data/briefings/${file}";`;
    })
    .join("\n");

  const byPeriod = files
    .map((file) => {
      const period = file.replace(".json", "");
      const varName = file.replace(".json", "").replace(/-/g, "_");
      return `  "${period}": briefing_${varName} as BriefingRecord,`;
    })
    .join("\n");

  const byFile = files
    .map((file) => {
      const varName = file.replace(".json", "").replace(/-/g, "_");
      return `  "${file}": briefing_${varName} as BriefingRecord,`;
    })
    .join("\n");

  const content = `/** AUTO-GENERATED by pipeline — do not edit manually */\nimport type { BriefingRecord } from "@/lib/data/schemas";\n\n${imports}\n\nexport const BRIEFINGS_BY_PERIOD: Record<string, BriefingRecord> = {\n${byPeriod}\n};\n\nexport const BRIEFINGS_BY_FILE: Record<string, BriefingRecord> = {\n${byFile}\n};\n`;

  await writeFile(REGISTRY_PATH, content, "utf8");
}

export async function readMetaFromDisk(): Promise<MetaRecord> {
  const raw = await readFile(path.join(DATA_ROOT, "meta.json"), "utf8");
  return JSON.parse(raw) as MetaRecord;
}

export async function readBriefingFromDisk(
  file: string
): Promise<BriefingRecord> {
  const raw = await readFile(path.join(BRIEFINGS_DIR, file), "utf8");
  return JSON.parse(raw) as BriefingRecord;
}

export async function wasPipelineBriefingBefore(
  period: string
): Promise<boolean> {
  try {
    const briefing = await readBriefingFromDisk(`${period}.json`);
    return briefing.dataProvenance !== "curated-mock";
  } catch {
    return false;
  }
}
